// preloader
import "../utils/preloader";
// burgerMenu
import "../burgerMenu/burgerMenu";
import "../burgerMenu/buttonsImplementation";
// circle
import "../circle/circle--serm";
// header
import "../header/text";
import "../header/animationWithScroll";
// local
import "../serm/buttonsImplementation";
import "../serm/cyclesItemAutoHeightAddForLeftSideSaladStick";
// functional
import "../attraction/spanBg";
import "../attraction/answersAccordion";
// footer
import "../footer/checkbox";
import "../footer/add-space-between-items";
import "../footer/changeFooterColumnsOrder";
import "../footer/rights-top-border";
// utils
import "../utils/allignButtonsSpan";
import "../utils/addInteractivityToButton";
import "../utils/butter";
import "../utils/animationOnScroll";
