import { addInteractivityToButton } from "../../utils/addInteractivityToButton";

if (window.innerWidth > 1070) {
  addInteractivityToButton(
    ".fillingButton--intro-1",
    ".fillingButton__svg-circle--intro-1",
    ".fillingButton__circle--intro-1",
    2,
    1,
    0,
    -65,
    true,
    "blackArrow",
    false
  );
  addInteractivityToButton(
    ".fillingButton--intro-2",
    ".fillingButton__svg-circle--intro-2",
    ".fillingButton__circle--intro-2",
    2,
    1,
    0,
    -65,
    true,
    "blackArrow",
    false
  );
  addInteractivityToButton(
    ".fillingButton--intro-3",
    ".fillingButton__svg-circle--intro-3",
    ".fillingButton__circle--intro-3",
    2,
    1,
    0,
    -65,
    true,
    "blackArrow",
    false
  );
}

if (window.innerWidth <= 1070) {
  addInteractivityToButton(
    ".fillingButton--intro-1",
    ".fillingButton__svg-circle--intro-1",
    ".fillingButton__circle--intro-1",
    1,
    1,
    0,
    -65,
    true,
    "blackArrow",
    false
  );
  addInteractivityToButton(
    ".fillingButton--intro-2",
    ".fillingButton__svg-circle--intro-2",
    ".fillingButton__circle--intro-2",
    1,
    1,
    0,
    -65,
    true,
    "blackArrow",
    false
  );
  addInteractivityToButton(
    ".fillingButton--intro-3",
    ".fillingButton__svg-circle--intro-3",
    ".fillingButton__circle--intro-3",
    1,
    1,
    0,
    -65,
    true,
    "blackArrow",
    false
  );
} else if (window.innerWidth <= 620) {
  addInteractivityToButton(
    ".fillingButton--intro-1",
    ".fillingButton__svg-circle--intro-1",
    ".fillingButton__circle--intro-1",
    1,
    1,
    0,
    -10,
    true,
    "blackArrow",
    false
  );
  addInteractivityToButton(
    ".fillingButton--intro-2",
    ".fillingButton__svg-circle--intro-2",
    ".fillingButton__circle--intro-2",
    1,
    1,
    0,
    -10,
    true,
    "blackArrow",
    false
  );
  addInteractivityToButton(
    ".fillingButton--intro-3",
    ".fillingButton__svg-circle--intro-3",
    ".fillingButton__circle--intro-3",
    1,
    1,
    0,
    -10,
    true,
    "blackArrow",
    false
  );
} else if (window.innerWidth <= 380) {
  addInteractivityToButton(
    ".fillingButton--intro-1",
    ".fillingButton__svg-circle--intro-1",
    ".fillingButton__circle--intro-1",
    1,
    1,
    0,
    -50,
    true,
    "blackArrow",
    false
  );
  addInteractivityToButton(
    ".fillingButton--intro-2",
    ".fillingButton__svg-circle--intro-2",
    ".fillingButton__circle--intro-2",
    1,
    1,
    0,
    -50,
    true,
    "blackArrow",
    false
  );
  addInteractivityToButton(
    ".fillingButton--intro-3",
    ".fillingButton__svg-circle--intro-3",
    ".fillingButton__circle--intro-3",
    1,
    1,
    0,
    -50,
    true,
    "blackArrow",
    false
  );
}

window.addEventListener("resize", () => {
  if (window.innerWidth > 1070) {
    addInteractivityToButton(
      ".fillingButton--intro-1",
      ".fillingButton__svg-circle--intro-1",
      ".fillingButton__circle--intro-1",
      2,
      1,
      0,
      -65,
      false
    );
    addInteractivityToButton(
      ".fillingButton--intro-2",
      ".fillingButton__svg-circle--intro-2",
      ".fillingButton__circle--intro-2",
      2,
      1,
      0,
      -65,
      false
    );
    addInteractivityToButton(
      ".fillingButton--intro-3",
      ".fillingButton__svg-circle--intro-3",
      ".fillingButton__circle--intro-3",
      2,
      1,
      0,
      -65,
      false
    );
  }

  if (window.innerWidth <= 1070) {
    addInteractivityToButton(
      ".fillingButton--intro-1",
      ".fillingButton__svg-circle--intro-1",
      ".fillingButton__circle--intro-1",
      1,
      1,
      0,
      -65,
      false
    );
    addInteractivityToButton(
      ".fillingButton--intro-2",
      ".fillingButton__svg-circle--intro-2",
      ".fillingButton__circle--intro-2",
      1,
      1,
      0,
      -65,
      false
    );
    addInteractivityToButton(
      ".fillingButton--intro-3",
      ".fillingButton__svg-circle--intro-3",
      ".fillingButton__circle--intro-3",
      1,
      1,
      0,
      -65,
      false
    );
  }

  if (window.innerWidth <= 620) {
    addInteractivityToButton(
      ".fillingButton--intro-1",
      ".fillingButton__svg-circle--intro-1",
      ".fillingButton__circle--intro-1",
      1,
      1,
      0,
      -10,
      false
    );
    addInteractivityToButton(
      ".fillingButton--intro-2",
      ".fillingButton__svg-circle--intro-2",
      ".fillingButton__circle--intro-2",
      1,
      1,
      0,
      -10,
      false
    );
    addInteractivityToButton(
      ".fillingButton--intro-3",
      ".fillingButton__svg-circle--intro-3",
      ".fillingButton__circle--intro-3",
      1,
      1,
      0,
      -10,
      false
    );
  }

  if (window.innerWidth <= 380) {
    addInteractivityToButton(
      ".fillingButton--intro-1",
      ".fillingButton__svg-circle--intro-1",
      ".fillingButton__circle--intro-1",
      1,
      1,
      0,
      -50,
      false
    );
    addInteractivityToButton(
      ".fillingButton--intro-2",
      ".fillingButton__svg-circle--intro-2",
      ".fillingButton__circle--intro-2",
      1,
      1,
      0,
      -50,
      false
    );
    addInteractivityToButton(
      ".fillingButton--intro-3",
      ".fillingButton__svg-circle--intro-3",
      ".fillingButton__circle--intro-3",
      1,
      1,
      0,
      -50,
      false
    );
  }
});
