// preloader
import "../utils/preloader";
// burgerMenu
import "../burgerMenu/burgerMenu";
import "../burgerMenu/buttonsImplementation--servicesPage";
// circle
import "../circle/circle--services";
// header
import "../header/text";
import "../header/animationWithScroll";
// intro
import "./animatedStatistics";
// footer
import "../footer/checkbox";
import "../footer/add-space-between-items";
import "../footer/changeFooterColumnsOrder";
import "../footer/rights-top-border";
// utils
import "../utils/allignButtonsSpan";
import "../utils/butter";
import "../utils/animationOnScroll";
import "./buttonsImplementation";
