// preloader
import "../utils/preloader"
// circle
import "../circle/circle"
// header
import "../header/burger"
import "../header/text"
import "../header/color-inversion"
// wide-screen-burger
import "../wide-screen-burger/wide-screen-burger.min"
import "../wide-screen-burger/wide-screen-burger"
import "../wide-screen-burger/button"
// intro
import "./intro/splideMain"
import "./intro/splideItems"
import "./intro/button"
import "./intro/alignSliderPaginationsBullets"
import "./intro/arrowForScrollToNextSection"
// about us
import "./about-us/decoration-image"
import "./about-us/running-line"
import "./about-us/button"
//services
import "./services/lines"
import "./services/button"
import "./services/parallax"
// products
import "./products/button"
import "./products/animation-for-items"
import "./products/aos"
// reviews
import "./reviews/decoration-image"
import "./reviews/splide"
import "./reviews/splide-arrows-align"
import "./reviews/splide-arrows-embed"
// blog
import "./blog/button"
// footer
import "../footer/checkbox"
import "../footer/add-space-between-items"
import "../footer/changeFooterColumnsOrder"
import "../footer/rights-top-border"
// utils
import "../utils/allign-buttons-span"
