// circle
import "./circle/circle"
// header
import "./header/burger"
import "./header/color-inversion"
// wide-screen-burger
import "./wide-screen-burger/wide-screen-burger.min"
import "./wide-screen-burger/wide-screen-burger"
// intro
import "./intro/splide"
import "./intro/swiper-pagination-to-left-side"
import "./intro/to-next-section"
// about us
import "./about-us/decoration-image"
import "./about-us/running-line"
import "./about-us/button"
//services
import "./services/lines"
import "./services/button"
import "./services/parallax"
// products
import "./products/button"
import "./products/animation-for-items"
import "./products/aos"
// reviews
import "./reviews/decoration-image"
import "./reviews/splide"
import "./reviews/splide-arrows"
// blog
import "./blog/button"
// footer
import "./footer/rights-top-border"
import "./footer/checkbox"