// preloader
import "../utils/preloader";
// burgerMenu
import "../burgerMenu/burgerMenu";
import "../burgerMenu/buttonsImplementation";
// circle
import "../circle/circle";
// header
import "../header/text";
import "../header/animationWithScroll";
// intro
import "./intro/splideItems";
import "./intro/splideMain";
import "./intro/buttonsImplementation";
import "./intro/alignSliderPaginationsBullets";
import "./intro/arrowForScrollToNextSection";
// about us
import "./about-us/decoration-image";
import "./about-us/running-line";
import "./about-us/buttonsImplementation";
//services
import "./services/spanBg";
import "./services/buttonsImplementation";
// products
import "./products/buttonsImplementation";
import "./products/animation-for-items";
import "./products/aos";
// reviews
import "./reviews/decoration-image";
import "./reviews/splide";
import "./reviews/splide-arrows-align";
import "./reviews/splide-arrows-embed";
// blog
import "./blog/buttonsImplementation";
// footer
import "../footer/checkbox";
import "../footer/add-space-between-items";
import "../footer/changeFooterColumnsOrder";
import "../footer/rights-top-border";
// utils
import "../utils/allignButtonsSpan";
import "../utils/addInteractivityToButton";
import "../utils/butter";
